apiVersion: v1
kind: Service
metadata:
  name: {{env "REPONAME"}}
  namespace: {{env "REPONAME"}}
  labels:
    app: {{ env "REPONAME" }}
    team: {{if .Env.TEAM}}{{env "TEAM"}}{{else}}undefined{{end}}
    slackchannel: {{if .Env.SLACKCHANNEL}}{{env "SLACKCHANNEL"}}{{else}}undefined{{end}}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vev-cm-sftp.{{env "ENV"}}.medialaben.no.
spec:
  type: LoadBalancer
  ports:
    - port: 22
      protocol: TCP
      targetPort: ssh
  selector:
    app: {{env "REPONAME"}}
